apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-deployment
  labels:
    app: apache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app:  apache
    spec:
      containers:
        - name:  apache
          image: amarsingh3d/apache2.4-php7.2
          ports:
           - containerPort: 80
             name:  apache

---
apiVersion: v1
kind: Service
metadata:
  name:  phpservice
spec:
  selector:
    app: apache
  ports:
   - protocol: TCP
     port:  80
     targetPort: 80
     nodePort: 30060
  type:  LoadBalancer