apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app:  mysql
    spec:
      containers:
        - name:  mysql
          image: mysql:5.6
          ports:
           - containerPort: 3306
             name:  mysql
          env:
            - name: MYSQL_ROOT_PASSWORD   
              value: "redhat"

---
apiVersion: v1
kind: Service
metadata:
  name:  mysql-service
spec:
  selector:
    app: mysql
  ports:
   - protocol: TCP
     port: 3306
     targetPort: 3306
     nodePort: 30020
  type: NodePort
             